### PR TITLE
Add `static` feature flag

### PR DESCRIPTION
**Pull request by SabrinaJewson**
This is not the same solution as in #228, but it works perfectly fine for me. Also, note that I’m not too well-versed in linking so I may have made a mistake here.

Closes: #228

### CODE REVIEW

**Comment by filmil** [comment]
Thank you for this contribution and the other PRs you sent. Please allow me some time to get around to reviewing them. Thanks for your patience!

**Comment by SabrinaJewson** [comment]
Ah, I just realized that while my distribution has the system ICU compiled with `-fPIC` (so it works perfectly fine with Rust), some distributions don’t (like Ubuntu) — that means static linking won’t work for them, and we’ll have to add another feature flag to enable building from source. So I’ll convert this to a draft for now.

**Comment by filmil** [comment]
OK, let me know what you want to do with the PR once it's ready.

**Comment by filmil** [comment]
Ping?

**Comment by SabrinaJewson** [comment]
Right, sorry, I forgot to update this. So I tried adding automatic building of ICU to the build script via another feature flag, but the thing is that turns out to be _very_ slow and also annoying because it doesn’t give any output during the build process. I think the best course of action here is to merge this for the use case where people _do_ have a prebuilt PIC ICU available, and then figure out what to do about building from source separately.

**Comment by mpalmer** [comment]
This PR landed at a *really* great time, as I'm in need of static-linked ICU in a Rust project.  Thanks for putting it together, @SabrinaJewson.  Do you have any indication, @filmil, of when this PR is likely to make it into a release?

**Comment by filmil** [comment]
I'm afk for the next 3-4 days but and will try to release thereabouts.

**Pull request merged**
