### PR TITLE
collation: add sort key support

### PR DESCRIPTION
**Pull request by vmiklos**
By adding a safe wrapper around ucol_getSortKey().

### CODE REVIEW

**Comment by vmiklos** [comment]
Thanks! :-) Just curious, do you have any plans when would you cut a next v1.x.y release (from rust_icu_ucol or in general)?

**Comment by filmil** [comment]
New releases are cut on an as needed basis - I'd be glad to make one if you need it, but please allow some time for that to happen.

**Comment by vmiklos** [comment]
Makes sense, no rush. :-) I need this because I'm porting a python prototype to rust and pyicu provides this API. But no problem to just use git master as an interim solution till you're comfortable to push a new tag. Thanks!

**Comment by vmiklos** [comment]
Ping, could you please cut a new release at some stage?

I still have this as a TODO at

https://github.com/vmiklos/osm-gimmisn/blob/224017da7fe9ed46981767f3a0d75d855374b40d/Cargo.toml#L40-L43

Thanks.

**Comment by filmil** [comment]
Oops, I forgot.  I'll try to do it next week, fwiw I have a few other minor improvements lined up.

**Comment by filmil** [comment]
FYI, 1.0.1 is now published.

**Comment by vmiklos** [comment]
Thanks a lot! :-)

**Pull request merged**
