### PR TITLE
Implement character encoding conversion (`ucnv.h`)

### PR DESCRIPTION
**Pull request by lacc97**
This PR implements wrapping functions and types on top of ICU's `ucnv.h` header (solves #229).

This PR adds a new crate called `rust_icu_ucnv` in line with the naming convention of the other crates in this project.

The main type is UConverter, which can be created using `UConverter::open` with an encoding name (as a `&str`). This type provides conversion functions between UTF-16 and the provided encoding.

This crate also provides `utf8::Converter` as a convenience type to work directly with UTF-8 strings, such as with Rust’s `&str` and `String` types.

### CODE REVIEW

**Comment by lacc97** [comment]
Okay, I have signed the CLA now.

**Comment by filmil** [comment]
You will need to rerun `make static-bindgen` to generate the newly-available functions for the pre-generated bindings.

To do that, please edit `rust_icu_sys/bindgen/run_bindgen.sh`  the same way you did with `build.rs` files - adding the missing header names and regexes.
This will allow the remaining builders to pass.

**Comment by filmil** [comment]
Also, thank you for your patience for the review.

**Comment by lacc97** [comment]
I haven't been able to get the docker environment set up properly. It complains with 
```
env: './rust_icu/rust_icu_sys/bindgen/run_bindgen.sh': Permission denied
```
when I run `make static-bindgen`.

I've only updated the run_bindgen.sh file.

**Comment by lacc97** [comment]
Wait, nevermind. I think I got it working in the end.

**Pull request merged**
